### ISSUE TITLE
长帖子可以配置显示摘要模式

### ISSUE THREAD

**Issue by mave99a** [blocklet/publish-kit#10]
长帖子可以配置显示摘要模式，更符合blog 的典型风格

<img width="560" alt="image" src="https://user-images.githubusercontent.com/41923/165459488-d6cdd21d-658f-4a4c-a5ea-0016fe0ad5fb.png">

**Comment by ee07b577** [comment]
目前的机制是：前端将 markdown语法 传给服务端，服务端直接存储。想在 feeds 流中显示摘要，需要在
1、前端发送创建请求 或者 
2、服务端收到创建请求 或者 
3、feeds列表展示环节生成 摘要（excerpt）。
最好的方法是在环节1 生成摘要。

摘要应该是纯文字的，因此需要过滤掉markdown语法插入的标记符号以及html标签。最好的办法是preview之后 trim-html(https://github.com/brankosekulic/trimHtml)。
preview 可以用这个组件： react-markdown-preview (https://github.com/uiwjs/react-markdown-preview)。
我们想在创建时 preview 得到 html,从而得到 excerpt，创建一个display:none 的dom 承载 preview生成的 div#blog-preview。

还有一种方式，让用户自己定义 excerpt，需要讨论设计方案（custom ）

**Comment by ee07b577** [comment]
修复，待PR合并
<img width="928" alt="image" src="https://user-images.githubusercontent.com/1484821/173493254-489976f6-323e-4f01-b0d2-d32ad0795faa.png">
