### ISSUE TITLE
没有采用有权限的passport，应该发布界面禁止掉，而不是到发布时出现“no permission”

### ISSUE THREAD

**Issue by mave99a** [blocklet/publish-kit#17]
<img width="906" alt="image" src="https://user-images.githubusercontent.com/41923/168557666-23dd252b-086e-4f37-a1a4-58e4d08bb136.png">

**Comment by mave99a** [comment]
图片upload后，preview 不能显示，可能是相同原因

<img width="597" alt="image" src="https://user-images.githubusercontent.com/41923/168557948-1b1b2159-f601-488b-800d-d943c1ef7d68.png">

**Comment by ee07b577** [comment]
待合PR 
<img width="893" alt="image" src="https://user-images.githubusercontent.com/1484821/173714028-43886555-743e-49e5-ba06-27dcf6ee5ba3.png">
