### ISSUE TITLE
长图出现的问题

### ISSUE THREAD

**Issue by mave99a** [blocklet/publish-kit#18]
<img width="963" alt="image" src="https://user-images.githubusercontent.com/41923/168718626-e3fb88cb-0289-42f7-b992-d8a596a56620.png">

**Comment by mave99a** [comment]
发布后：

<img width="660" alt="image" src="https://user-images.githubusercontent.com/41923/168718768-e3ecbe60-fab4-44f8-99f3-442ca89ebef7.png">

**Comment by ee07b577** [comment]
log:未复现

**Comment by kirakiray** [comment]
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/5945154/195797340-8abbe50d-11aa-464a-bb0c-a6c6d58f862f.png">

尝试各种尺寸都没有出现上述问题，应该已被修复
