### ISSUE TITLE
publish-kit参与组合后的问题

### ISSUE THREAD

**Issue by mave99a** [blocklet/publish-kit#22]
一开始用static demo + publish kit，可以正常工作。 

加入compositdemo后，publishkit页面出现这个错误：

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41923/178142764-c247e849-bcf9-4979-8ada-98e183c785e3.png">

其他blocklet正常

出现问题组合的实例在： 
https://node-dev-1.arcblock.io/admin/blocklets/z8iZz8keqi1YMViajVLoGX5AYBTBAUennTu2o/components

**Comment by wangshijun** [comment]
@kirakiray 这个问题验证下最新版在下面组合的情况下能否 work 即可：

- [ ] 把单个 publishkit 组合到某个应用里面（动态挂载的方式）
- [ ] 把多个 publishkit 组合到某个应用里面（动态挂载的方式）
- [ ] 把 publishkit 组合到自己下面（参数配置不同）

**Comment by wangshijun** [comment]
今天 bug bash 验证了下，test store 的版本落后比较多，存在相同问题，prod store 是最新版，组合正常。需要把 test store 的给删除掉。
