### ISSUE TITLE
明明我已经login 了，但还是显示这个login按钮

### ISSUE THREAD

**Issue by mave99a** [blocklet/publish-kit#26]
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/41923/185708211-e196ffb2-8513-4720-9534-37c74405c677.png">

**Comment by kirakiray** [comment]
最新代码在未登录时已经去掉login按钮了，这个是 issuse 还是 feature ？

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/5945154/196073300-cbe8fed4-83df-4079-ae3d-adc72c89015b.png">

测试下来无论是否登陆，login按钮都已经消失

**Comment by wangshijun** [comment]
都放到右上角了
