### ISSUE TITLE
写blog 的时候，把标题放在上面，符合blog的写作习惯

### ISSUE THREAD

**Issue by mave99a** [blocklet/publish-kit#33]
写blog 的时候，把标题放在上面，符合blog的写作习惯

现在先写内容，再写标题 不符合习惯

**Comment by kirakiray** [comment]
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/5945154/196074387-813c0ef2-c6d1-4e70-a4d7-5f807d7ad52a.png">

最新代码title已在顶部；
