### ISSUE TITLE
在被组合的时候， title应该是组合设定的名字，而不是publish kit本身。 

### ISSUE THREAD

**Issue by mave99a** [blocklet/publish-kit#43]
v 在被组合的时候， title应该是组合设定的名字，而不是publish kit本身。 

类似获得当前的app图标一样，这里的title 应该变成应用里指定的 （也许需要blocklet server支持？0

**Comment by wangshijun** [comment]
@kirakiray 验证下这个问题，可能已经解决了

**Comment by kirakiray** [comment]
验证已解决

<img width="960" alt="image" src="https://user-images.githubusercontent.com/5945154/197438030-f6eee02f-b92a-4c7d-8c5f-1d907c8d6b49.png">
