### ISSUE TITLE
关于编辑器的改造

### ISSUE THREAD

**Issue by kirakiray** [blocklet/publish-kit#57]
当前 Editor 有和业务有一定耦合（缓存那部分逻辑），编辑器主模块应该解耦成独立模块，这样就可以编辑功能就不需要跳转，而是直接在列表上做。

顺便做移动端兼容的问题；

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/5945154/197187330-0ff010e2-9bc2-4b32-bcec-cf84e432517c.png">

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/5945154/197187418-8a0cb850-d676-4393-a886-dee5a53195f9.png">

**Comment by wangshijun** [comment]
In-place-editor 只适合于短文，长文章可能还是新页面会更好？另外需要考虑下 publish-kit 朝和其他部件更好组合的方向演化

**Comment by mave99a** [comment]
text editor 是不是可以plugable / composable。 

可以做个特别好用的editor， medium和https://vocus.cc/ 的编辑器真好用

**Comment by mave99a** [comment]
的确publishkit 可以定一个editor 的plug 界面，这样可以用不同的editor，比如有的可以就是简单MD 风格的，有的是写文章风格的，有的是类似 exposure.com 的story风格的。 

因为不可能有一个 one fit all 的超级editor，editor一直是个难题。 pubish kit可以focus 于publish，editor 可以专注于edit，还可以有多种
