### ISSUE TITLE
[ Discuss ] 预览 blog 是否可以放到前端转译？

### ISSUE THREAD

**Issue by kirakiray** [blocklet/publish-kit#58]
现在是通过在 create 的时候将预览的 html 保存到数据库，后期对样式做调整的话，以前发的blog还是旧的样式，而且样式会有一些奇怪问题；

<img width="920" alt="image" src="https://user-images.githubusercontent.com/5945154/197188764-05041fd4-d4de-412d-870a-0f95201cb72f.png">

### 整改思维：

是否直接使用markdown作为源码，在前端组件进行渲染转换？已经有这类的库可以直接使用 [marked](https://marked.js.org/)； 这种可能是对搜索引擎优化不友好，不知道爬虫趴下来markdown的源码会不会自动修正。

**Comment by wangshijun** [comment]
我觉得可以

**Comment by kirakiray** [comment]
已添加blocks类型，就是从前端转译的，后期用于替换blog；
